---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: https-rs
  labels:
    app: httpd
spec:
  minReadySecond: 5
  replicas: 2
  selector:
    matchLabels:
      app: httpd




























      