---
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels: # used to filter/select objects
    environment: Developer
    team: dev-ops
    project: adept-ecommerce
  annotations:
    imageregistry: "https://hub.docker.com/" # subjective information
spec:
  containers: 
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
