---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-command--probe
spec: # specifications
  - name: ubuntu-container # container name
    image: ubuntu: latest # ubuntu os image
    command:
      - /bin/bash 
      - ec
      - sleep 30; touch /tmp/ready/; sleep 600 # execute this command using bash promt
    readinessProbe: # either application run inside container or not 
      exec: # health check command
        - cat
        - /tmp/ready # when file exist then this command will return success
    initialDelaySecond: 10
    periodSecond: 5 # perform health check in every five second.

    ### liveness probe check your container working or not

    ### salt stack - salt
    ### mist.io - cmp / mcp 
    ### 
    