---
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  container:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 8080
          protocol: TCP
      
      name: nginx
      image: nginx
      ports:
        - containerPort: 80

      name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "adept@123"
          




