---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels:
    environment: Developer
    team: dev-ops
    project: adept-ecommerce
spec:
  containers: 
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
